[2024-08-29T15:03:52.408+0000] {processor.py:186} INFO - Started process (PID=682) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:03:52.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:03:52.411+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:03:52.411+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:03:52.667+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:03:52.658+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 8, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:03:52.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:03:52.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.290 seconds
[2024-08-29T15:04:23.537+0000] {processor.py:186} INFO - Started process (PID=745) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:04:23.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:04:23.540+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:04:23.540+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:04:23.598+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:04:23.591+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 8, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:04:23.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:04:23.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.093 seconds
[2024-08-29T15:04:54.434+0000] {processor.py:186} INFO - Started process (PID=808) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:04:54.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:04:54.437+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:04:54.436+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:04:54.532+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:04:54.501+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 8, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:04:54.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:04:54.553+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.124 seconds
[2024-08-29T15:05:24.654+0000] {processor.py:186} INFO - Started process (PID=871) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:05:24.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:05:24.657+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:05:24.657+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:05:24.713+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:05:24.709+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 8, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:05:24.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:05:24.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.089 seconds
[2024-08-29T15:05:55.222+0000] {processor.py:186} INFO - Started process (PID=934) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:05:55.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:05:55.225+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:05:55.225+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:05:55.288+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:05:55.284+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 8, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:05:55.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:05:55.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.087 seconds
[2024-08-29T15:06:01.782+0000] {processor.py:186} INFO - Started process (PID=951) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:06:01.783+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:06:01.785+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:06:01.785+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:06:01.862+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:06:01.856+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:06:01.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:06:01.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.103 seconds
[2024-08-29T15:06:32.035+0000] {processor.py:186} INFO - Started process (PID=1006) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:06:32.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:06:32.038+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:06:32.038+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:06:32.103+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:06:32.097+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:06:32.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:06:32.120+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.089 seconds
[2024-08-29T15:07:02.586+0000] {processor.py:186} INFO - Started process (PID=1069) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:07:02.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:07:02.589+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:07:02.589+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:07:02.670+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:07:02.664+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:07:02.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:07:02.687+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.105 seconds
[2024-08-29T15:07:33.342+0000] {processor.py:186} INFO - Started process (PID=1132) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:07:33.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:07:33.346+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:07:33.345+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:07:33.424+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:07:33.417+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:07:33.427+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:07:33.444+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.106 seconds
[2024-08-29T15:08:03.759+0000] {processor.py:186} INFO - Started process (PID=1195) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:08:03.760+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:08:03.762+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:08:03.762+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:08:03.842+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:08:03.835+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:08:03.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:08:03.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.114 seconds
[2024-08-29T15:08:34.157+0000] {processor.py:186} INFO - Started process (PID=1258) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:08:34.158+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:08:34.160+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:08:34.160+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:08:34.222+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:08:34.216+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:08:34.223+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:08:34.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.090 seconds
[2024-08-29T15:09:04.673+0000] {processor.py:186} INFO - Started process (PID=1321) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:09:04.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:09:04.676+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:09:04.675+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:09:04.735+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:09:04.727+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:09:04.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:09:04.751+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.082 seconds
[2024-08-29T15:09:35.583+0000] {processor.py:186} INFO - Started process (PID=1385) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:09:35.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:09:35.587+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:09:35.586+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:09:35.660+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:09:35.655+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:09:35.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:09:35.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.100 seconds
[2024-08-29T15:10:05.902+0000] {processor.py:186} INFO - Started process (PID=1448) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:10:05.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:10:05.904+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:10:05.904+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:10:06.059+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:10:06.051+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:10:06.061+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:10:06.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.182 seconds
[2024-08-29T15:11:15.127+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:11:15.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:11:15.129+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:11:15.129+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:11:15.273+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:11:15.270+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:11:15.274+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:11:15.289+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.166 seconds
[2024-08-29T15:11:46.266+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:11:46.267+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:11:46.269+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:11:46.269+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:11:46.336+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:11:46.331+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:11:46.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:11:46.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.092 seconds
[2024-08-29T15:12:17.037+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:12:17.039+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:12:17.041+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:12:17.041+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:12:17.127+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:12:17.119+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:12:17.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:12:17.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.117 seconds
[2024-08-29T15:12:47.786+0000] {processor.py:186} INFO - Started process (PID=252) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:12:47.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:12:47.789+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:12:47.789+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:12:47.847+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:12:47.844+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:12:47.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:12:47.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.082 seconds
[2024-08-29T15:13:17.998+0000] {processor.py:186} INFO - Started process (PID=315) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:13:17.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:13:18.001+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:13:18.001+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:13:18.073+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:13:18.066+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:13:18.091+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:13:18.107+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.113 seconds
[2024-08-29T15:13:49.087+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:13:49.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:13:49.090+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:13:49.090+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:13:49.154+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:13:49.150+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:13:49.155+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:13:49.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.091 seconds
[2024-08-29T15:14:19.457+0000] {processor.py:186} INFO - Started process (PID=447) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:14:19.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:14:19.460+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:14:19.460+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:14:19.529+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:14:19.521+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:14:19.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:14:19.547+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.094 seconds
[2024-08-29T15:14:50.501+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:14:50.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:14:50.504+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:14:50.504+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:14:50.573+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:14:50.568+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:14:50.575+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:14:50.590+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.094 seconds
[2024-08-29T15:15:21.515+0000] {processor.py:186} INFO - Started process (PID=573) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:15:21.520+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:15:21.527+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:15:21.526+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:15:21.625+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:15:21.618+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:15:21.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:15:21.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.133 seconds
[2024-08-29T15:15:51.944+0000] {processor.py:186} INFO - Started process (PID=636) to work on /opt/airflow/dags/download_dag.py
[2024-08-29T15:15:51.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/download_dag.py for tasks to queue
[2024-08-29T15:15:51.947+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:15:51.947+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/download_dag.py
[2024-08-29T15:15:52.003+0000] {logging_mixin.py:190} INFO - [2024-08-29T15:15:51.997+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/download_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/download_dag.py", line 11, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-08-29T15:15:52.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/download_dag.py
[2024-08-29T15:15:52.020+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/download_dag.py took 0.081 seconds
